# Generated by Django 4.2.11 on 2024-03-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttype',
            name='abbreviation',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
