# Generated by Django 4.2.11 on 2024-03-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_equipmenttype_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='threshold',
            field=models.IntegerField(default=10),
        ),
    ]
